### ISSUE TITLE
GraphiQL explorer keeps refreshing on every selection

### ISSUE THREAD

**Issue by tr1s** [harshil1712/contentful-gql-playground#3]
Hi there, thanks for the great plugin, I love using the GraphiQL file explorer!

One main issue with it is that **every selection I make will refresh and I have to scroll and find the position I was in again.**

Here's a video example:

https://user-images.githubusercontent.com/19172250/233105082-6b48c136-a7ba-436f-bdea-06896f91083d.mp4

Hopefully this issue can get sorted out, it would be perfect after that.

Cheers,

**Comment by harshil1712** [comment]
Hey! Thank you for opening up the issue. I'll try to fix this as soon as I can.

**Comment by tr1s** [comment]
Sounds good thank you

**Comment by tr1s** [comment]
@harshil1712 I just wanted to bump this for visibility one more time, I get a lot of value out of this plugin and fixing the refreshing bug would make it perfect in my eyes!

Cheers 🙏🏽

**Comment by harshil1712** [comment]
Hey @tr1s, I've moved the app to Nextjs and updated the packages. It should now solve the issue you reported. Can you try out the  [nextjs](https://github.com/harshil1712/gql-playground/tree/nextjs) branch?

**Comment by harshil1712** [comment]
Hey @tr1s, I've merged the changes to the main app. It should now fix the issues you had.

**Comment by tr1s** [comment]
I can confirm on my end it's fixed now @harshil1712.

Thank you very much!
